package:
  name: devopscc
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - devopscc

about:
  home: add_url_here
  license: BSD-3-Clause License
